Parte 12 - JWT
jornada-java/livro-java-exemplos pull request #10
Opened 2020-02-14 19:08 UTC by jonasdeveloper

# Código fonte usado na parte 12 - JWT

2020-02-14 19:16 UTC, bkbustamante approved these changes

2020-02-16 13:38 UTC, sandrogiacom requested changes

2020-02-16 13:38 UTC, sandrogiacom commented on Parte 12 - Segurança de Aplicações JWT/src/main/java/io/jornadas/jwt/security/JWTUtil.java
> +	public static String a(Usuario usuario) {
Nome de método sem significado

2020-02-16 13:38 UTC, sandrogiacom commented on Parte 12 - Segurança de Aplicações JWT/src/main/java/io/jornadas/jwt/security/JWTUtil.java
> +	public static String generateToken(Usuario usuario) {
Padrão de metodos em portugues

2020-02-16 13:38 UTC, sandrogiacom commented on Parte 12 - Segurança de Aplicações JWT/src/main/java/io/jornadas/jwt/repository/IUsuarioRepository.java
> +	List<Usuario> findAll();
Alguns métodos estão em Ingles

2020-02-16 20:35 UTC, jonasdeveloper commented on Parte 12 - Segurança de Aplicações JWT/src/main/java/io/jornadas/jwt/repository/IUsuarioRepository.java
> +	List<Usuario> findAll();
Alterado, obrigado!

2020-02-16 20:35 UTC, jonasdeveloper commented on Parte 12 - Segurança de Aplicações JWT/src/main/java/io/jornadas/jwt/security/JWTUtil.java
> +	public static String generateToken(Usuario usuario) {
Alterado, obrigado!

2020-02-16 20:35 UTC, jonasdeveloper commented on Parte 12 - Segurança de Aplicações JWT/src/main/java/io/jornadas/jwt/security/JWTUtil.java
> +	public static String a(Usuario usuario) {
Opa, esse ficou sobrando!

Removido valeu!

2020-02-16 20:36 UTC, jonasdeveloper commented
@sandrogiacom, ajustes realizados, obrigado!

2020-02-16 20:48 UTC, merged